# Generated by Django 6.0.2 on 2026-02-22 07:54

from django.db import migrations


def rehash_answers(apps, schema_editor):
    import bcrypt
    CustomUser = apps.get_model('fees', 'CustomUser')
    for user in CustomUser.objects.all():
        ans = user.security_answer
        if ans and not ans.startswith('$2b$'):
            # It's plain text, re-hash it
            # Using strip and lower to match the new behavior in models.py
            ans = str(ans).strip().lower()
            salt = bcrypt.gensalt()
            hashed = bcrypt.hashpw(ans.encode('utf-8'), salt)
            user.security_answer = hashed.decode('utf-8')
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rehash_answers),
    ]
