# Generated by Django 6.0.2 on 2026-02-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_globalsettings_student_address_student_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='manual_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
